# Done to increase the memory available to gradle.
org.gradle.jvmargs             = -Xmx4G
org.gradle.parallel            = true

org.gradle.configuration-cache = false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version              = 26.2
loader_version                 = 0.19.5
loom_version                   = 1.17.12

# Fabric API
compile_only_fabric_api        = false
fabric_version                 = 0.160.0+26.2

# Recipe Viewer
compile_only_rei               = true
rei_version                    = 20.0.811
jei_version                    = 26.1.2-fabric:29.6.2.31
eiv_version                    = 5.2.0+1.21.10
rrv_version                    = 8.3.1+26.2-pre-5

# Sodium
sodium_version                 = 0.9.2+mc26.2

# CrankShaft
crankshaft_version             = 1.5.8+mc26.2

# Iris
iris_version                   = 1.10.9+26.1-fabric

# CC: Tweaked
cct_version                    = 26.1.2-fabric:1.119.0

# Trinkets Updated
trinkets_version               = 4.1.0-beta.1+26.2

# Mod Properties
mod_version                    = 6.0.9
mod_id                         = 1
fork_revision                  = 1
maven_group                    = com.zurrtum
archives_base_name             = create-fly
